### ISSUE TITLE
Make label for issue, PR

### ISSUE THREAD

**Issue by rlaehgns5399** [gayeon1025/motion_front#2]
We are not using labels(I think @gayeon1025 will add it).

I suggest labels :)

| Label | Description |
| --- | --- |
| `Backend Issue` | Issue is about backend, not frontend |
| `Bug` | Something isn't working (Report) |
| `Design Fix` | Fix visual values (usually related to CSS) |
| `Document` | About document |
| `Enhancement` | New feature or request |
| `Fix Bug` | About fixing bug |
| `Future Work` | Things will be scheduled at future |
| `Hotfix` | Hotfix for production |
| `Project basis` | About project structure, packages, and config |
| `Refactor` | Refactoring code |
| `Discuss` | Discuss with others about specific subject |

**Comment by gayeon1025** [comment]
Thank you for letting me know. I added few labels.
The label of our repository is:

Label | Description
-----|-----
Good first issue | Recommended for beginners.
Project Basic | About project structure, packages, and config
Question | Any question for project
Discuss | Discuss with others about specific subject
Documentation | About documentation
Refactor | Refactoring code
Backend Issue | Issue is about backend, not frontend
Bug | Something isn't working (Report)
Hotfix | Hotfix for production
